# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='\u6307\u6570\u540d\u79f0')),
                ('loadUrl', models.CharField(max_length=1000, verbose_name='\u4e0b\u8f7d\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u6307\u6570\u914d\u7f6e',
                'verbose_name_plural': '[01].\u6307\u6570\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='IndexConst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, verbose_name='\u65e5\u671f')),
                ('code', models.CharField(max_length=20, verbose_name='\u4ee3\u7801')),
                ('weight', models.FloatField(verbose_name='\u6743\u91cd')),
                ('flashTime', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe6\x9b\xb4\xe6\x96\xb0')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexconst.Index', verbose_name='\u6307\u6570')),
            ],
            options={
                'verbose_name': '\u6307\u6570\u6210\u5206',
                'verbose_name_plural': '[02].\u6307\u6570\u6210\u5206',
            },
        ),
    ]
